myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path(' ', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>)/', views.cart_add, name='cart_add'),
    path('remove/(<int:product_id>)/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('shop/', include('shop.urls')),
    path('', RedirectView.as_view(url='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

myshop/shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.product_list, name='product_list'),
    path('product/<int:id>/', views.product_detail, name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/orders/models.py
from django.db import models
from shop.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Заказ {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

myshop/shop/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:

        ordering = ('name',)
    verbose_name = 'Категория'
    verbose_name_plural = 'Категории'

    def __str__(self):

        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):

        return self.name

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='Количество', min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['количество'], update_quantity=cd['изменить'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

myshop/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
           order = form.save()
           for item in cart:
              OrderItem.objects.create(order=order,
                                       product=item['product'],
                                       price=item['price'],
                                       quantity=item['quantity'])
           # очистка корзины
           cart.clear()
           return render(request, 'orders/order/created.html',
                  {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                  {'cart': cart, 'form': form})

myshop/shop/views.py
from .models import Category, Product
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }

    return render(request, 'shop/product/list.html', context)


def home(request):
    return render(request, 'shop/base.html')


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    return render(request, 'shop/product/detail.html', {'product': product})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Ваша корзина покупок
{% endblock %}
{% block content %}
<h1>Ваша корзина покупок</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена за единицу</th>
        <th>Цена</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                     {% static 'img/no_image.png' %}
                                {% endif %}">
            </a>
        </td>
        <td>{{ product.name }}</td>
        <td>{{ item.quantity }}</td>
        <td><a href="{% url 'cart:cart_remove' product.id%}">Удалить</a></td>
        <td class="num">${{ item.price }}</td>
        <td class="num">${{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Итого</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">Продолжить покупки</a>
    <a href="{% url 'orders:order_create' %}" class="button">Проверить</a>
</p>
{% endblock %}

myshop/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% block title %}Проверка заказа{% endblock %}
{% block content %}
<style>
     /* Общие стили для всего документа */
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f5f5f5;
        margin: 0;
        padding: 20px;
        color: #333;
}

    /* Заголовок заказа */
    .order-title {
        font-size: 2.5em;
        margin-bottom: 30px;
        text-align: center;
        color: #444;
}

    /* Контейнер информации о заказе */
    .order-info {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-bottom: 30px;
}

    /* Подзаголовок в контейнере заказа */
    .order-subtitle {
        font-size: 1.8em;
        margin-bottom: 20px;
        color: #555;
}

    /* Список товаров */
    .order-list {
        list-style: none;
        padding: 0;
        margin: 0;
}

    /* Элемент списка товаров */
    .order-item {
        display: flex;
        justify-content: space-between;
        padding: 15px 0;
        border-bottom: 1px solid #ddd;
        font-size: 1.1em;
}

    /* Количество товаров */
    .order-item-quantity {
        text-align: left;
        color: #888;
}

    /* Название товаров */
    .order-item-name {
        text-align: center;
        flex-grow: 2;
}

    /* Цена товаров */
    .order-item-price {
        text-align: right;
        color: #666;
        font-weight: bold;
}

    /* Общая сумма заказа */
    .order-total {
        font-size: 1.5em;
        font-weight: bold;
        text-align: right;
        margin-top: 20px;
        color: #333;
}

    /* Форма заказа */
    .order-form {
        display: flex;
        flex-direction: column;
        align-items: center;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

    /* Кнопка отправки */
    .submit-button {
        padding: 12px 25px;
        background-color: #007bff;
        border: none;
        color: white;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1em;
        margin-top: 20px;
        transition: background-color 0.3s ease;
}

    /* Стиль кнопки при наведении */
    .submit-button:hover {
        background-color: #0056b3;
}

    /* Стили формы */
    form p {
        width: 100%;
}

    form p input[type="text"], form p input[type="email"], form p input[type="password"], form p textarea {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ddd;
        border-radius: 4px;
}




</style>
<h1>Оформление заказа</h1>
<div class="order-info">
    <h3>Ваш заказ</h3>
    <ul>
        {% for item in cart %}
        <li>
            {{ item.quantity }}x {{ item.product.name }}
            <span>${{ item.total_price }}</span>
        </li>
        {% endfor %}
    </ul>
    <p>Всего: ${{ cart.get_total_price }}</p>
</div>
<form action="." method="post" class="order-form">
    <p>
        <label for="id_first_name">Имя:</label>
        <input type="text" name="first_name" maxlength="50" required id="id_first_name">


    </p>


    <p>
        <label for="id_last_name">Фамилия:</label>
        <input type="text" name="last_name" maxlength="50" required id="id_last_name">


    </p>


    <p>
        <label for="id_email">Электронная почта:</label>
        <input type="email" name="email" maxlength="254" required id="id_email">


    </p>


    <p>
        <label for="id_address">Адрес:</label>
        <input type="text" name="address" maxlength="250" required id="id_address">


    </p>


    <p>
        <label for="id_postal_code">Почтовый индекс:</label>
        <input type="text" name="postal_code" maxlength="20" required id="id_postal_code">


    </p>


    <p>
        <label for="id_city">Город:</label>
        <input type="text" name="city" maxlength="100" required id="id_city">
    <p><input type="submit" value="Оформить"></p>
    {% csrf_token %}
</form>
{% endblock %}

myshop/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% block title %}Спасибо за заказ!{% endblock %}
{% block content %}
 <h1>Спасибо за заказ!</h1>
 <p>Ваш заказ успешно сформирован. Номер вашего заказа
 <strong>{{ order.id }}</strong>.</p>
{% endblock %}

myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Мой магазин{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo">Мой магазин</a>
</div>
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Ваша корзина:
                <a href="{% url 'cart:cart_detail' %}">
                    {{ total_items }} item{{ total_items|pluralize }}, руб. {{ cart.get_total_price }}
                </a>
            {% else %}
                Ваша корзина пуста
            {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if product.category %}{{ product.category.name }}{% else %}Детали продукта{% endif %}
{% endblock %}
{% block content %}
<style>
    .product_detail {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        background-color: #fff;
        text-align: center;
    }

    .product_detail img {
        max-width: 100%;
        height: auto;
        border-radius: 10px;
        margin-bottom: 20px;
    }

    .product_detail h1 {
        font-size: 2em;
        margin-bottom: 10px;
    }

    .product_detail h2 a {
        color: #007bff;
        text-decoration: none;
    }

    .product_detail .price {
        font-size: 1.5em;
        color: #28a745;
        margin-bottom: 20px;
    }

    .product_detail form {
        margin-top: 20px;
    }

    .product_detail input[type="submit"] {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    .product_detail input[type="submit"]:hover {
        background-color: #0056b3;
    }
</style>
<div class="product_detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="{{ product.name }}">
    <h1>{{ product.name }}</h1>
    <p class="price">{{ product.price }} руб.</p>
    {{ product.description|linebreaks }}
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
    </form>
</div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Продукты{% endif %}
{% endblock %}
{% block content %}
<style>
    #main {
        display: flex;
        flex-wrap: wrap;
    }

    .product-list {
        display: flex;
        flex-wrap: wrap;
        gap: 16px;
    }

    .product-list .item {
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 10px;
        width: calc(33.333% - 80px);
        box-sizing: border-box;
        text-align: center;
        transition: box-shadow 0.3s;
    }

    .product-list .item img {
        max-width: 170px;
        height: 170px;
        display: block;
        margin: 0 auto 10px;
    }

    .product-list .item a {
        text-decoration: none;
        color: #333;
    }

    .product-list .item:hover {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    @media (max-width: 768px) {
        .product-list .item {
            width: calc(50% - 20px);
        }
    }

    @media (max-width: 480px) {
        .product-list .item {
            width: 100%;
        }
    }
</style>

<div id="sidebar">
    <h3>Категории</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url 'shop:product_list' %}">Все</a>
        </li>
        {% for c in categories %}
        <li {% if category and category.slug == c.slug %}class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Продукты{% endif %}</h1>
    {% for product in products %}
    <div class="item">
        <a href="{% url 'shop:product_detail' product.id %}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
        </a>
        <a href="{% url 'shop:product_detail' product.id %}">{{ product.name }}</a><br>
        {{ product.price }} руб.
    </div>
    {% endfor %}
</div>
{% endblock %}